---
# Container image for the workload controller
controllerImage: quay.io/ocsci/ocs-monkey-generator

ocs:
  namespace: openshift-storage

osio:
  image: quay.io/ocsci/osio-workload:latest
  workerInterarrival: 45
  workerLifetime: 86400
  workerActive: 1800
  workerIdle: 18000
  kernelSlots: 3
  kernelUntar: 6
  kernelRm: 6

# Parameters to configure chaos runner
chaos:
  # Set this parameter to install chaos runner
  enabled: false
  additionalFailure: 0.25
  checkInterval: 30
  cephclusterName: ocs-storagecluster-cephcluster
  mitigationTimeout: 900
  mttf: 150
  runtime: 0

workload:
  accessmode: ReadWriteOnce
  namespace: ocs-monkey
  runtime: 7200
  storageClass: ocs-storagecluster-ceph-rbd

# StorageClass for the workload generator's logs (and must-gather)
logPVCClass: gp2
